kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  selector:
    matchLabels:
      app: mysql
      version: "1.0"
      environment: testing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: "1.0"
        environment: testing
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-root
                  key: password
            - name: MYSQL_USER_ADMIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-admin
                  key: username
            - name: MYSQL_PASSWORD_ADMIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-admin
                  key: password
            - name: MYSQL_USER_CLIENT
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-client
                  key: username
            - name: MYSQL_PASSWORD_CLIENT
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-client
                  key: password
            - name: MYSQL_DATABASE
              value: JournalSystemDB
          ports:
            - containerPort: 3307
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  selector:
    app: mysql
    version: "1.0"
    environment: testing
  ports:
  - port: 3307
  selector:
    app: mysql
  clusterIP: None