apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-root
data:
  username: cm9vdA==  # base64-encoded username
  password: OTkwNTA1  # base64-encoded password

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-admin
data:
  username: YWRtaW4=  # base64-encoded username
  password: YWRtaW4=  # base64-encoded password

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-client
data:
  username: c2VhcmNoX2NsaWVudA==  # base64-encoded username
  password: c2VhcmNoX2NsaWVudA==  # base64-encoded password
